### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by yiwenwang47** [zjunlp/MolGen#12]
Hi,

Fascinating project! I was just wondering, how should I format the data for finetuning purposes? More specifically, what columns do I need? The CandidateDataset class asks for 'input' and 'candidates', but the files under moldata/finetune/ do not have these columns. If I have a custom property that I'd like to predict, what should I name it?

Thanks a lot!

**Comment by Fangyinfff** [comment]
Hi, 

Thank you for your interest. During the fine-tuning process, as shown in the figure, you can run `preprocess.sh`. 
<img width="810" alt="image" src="https://github.com/zjunlp/MolGen/assets/61076726/4d7bad87-adf4-4a00-9ea3-fde4c8389cc3">
This step generates candidate SMILES based on the input molecules. We have provided a sample input located at '../moldata/pretrain/zinc250k.csv'.

Please note that this model is not designed to predict properties. Instead, we rely on existing property functions to calculate the attribute values for each candidate. The candidates are then ranked based on these attribute values.

Best regards.

**Comment by zxlzr** [comment]
Hi, do you have any further questions?
