### ISSUE TITLE
Question about "loss_output" of "finetune.py"

### ISSUE THREAD

**Issue by YuhangXiao1103** [zjunlp/MolGen#13]
![image](https://github.com/zjunlp/MolGen/assets/125982410/b1363769-16ea-41f4-b7af-3ed840f485c9)
Bravor job! I'm curious that if the size of "src_id" and "candidate_id" are "[bs, num_input, max_len]" and "[bs, num_cand, max_len]", in which num_cand = num_samples*num_input. However, when the 2nd dimension of them are different, the programme doesn't make sense.

![image](https://github.com/zjunlp/MolGen/assets/125982410/ddea6e94-75bc-482a-9ab7-906fcb7a262e)
By the way, "input_ids" and "decoder_input_ids" don't seem to be used in finetune.py.

Hope for your reply!

**Comment by Fangyinfff** [comment]
Hi, thank you for your attention!

1. Could you please clarify what you mean by `num_samples`? Typically, a single source corresponds to multiple candidates, and these candidates are aligned with the source during processing.
2. Although we do not directly use `decoder_input_ids`, we have introduced the [`mle_loss`](https://github.com/zjunlp/MolGen/blob/main/MolGen/finetune.py#L304) in fine-tuning through another way. The `gold` used in calculating `mle_loss` effectively serves the same purpose as `decoder_input_ids`.

**Comment by YuhangXiao1103** [comment]
Yeah, num_samples mean the number of sampled multiple candidates with one source given.
So, when model receives the "src_ids" and "candidate_id", you mean each candidate in "candidate_id" corresponds to a single source for like batch[0], like duplicating the source to correspond to each candidate?

**Comment by YuhangXiao1103** [comment]
And I wanna know if it's correct that the given `candidate_ids` are just tokenized by tokenizer ,and don't need to shift right with `<bos>` token filled up?

**Comment by Fangyinfff** [comment]
We can refer to [this code](https://github.com/zjunlp/MolGen/blob/main/MolGen/src/data.py#L215-L248) to understand the process. Imagine we have a table named `data` with one column called `input` and another called `candidates`. The `input` column corresponds to the source, and the `candidates` column contains multiple candidate molecules. Each row looks something like this: `(candidate1, score1), (candidate2, score2), (candidate3, score3), ...` All these candidates correspond to the same source. Then, we sort by score and extract the candidates for tokenization. The `candidate_ids` do not need to be shifted to the right.

**Comment by YuhangXiao1103** [comment]
As you say " all candidiates correspond to the same source", then the size of `src_input_ids` is [b_s, 1, max_len] and `candidate_ids` is [b_s, num_cands, max_len]. Or duplicate the 2nd dimension of `src_input_ids` to [b_s, num_cands, max_len], then the size of them are matched. When I use the version of 1st, the model can't process this.

**Comment by Fangyinfff** [comment]
You can see that I performed a squeeze operation [here](https://github.com/zjunlp/MolGen/blob/main/MolGen/src/data.py#L234), so the size of `src_input_ids` are [batch_size, max_len], and the size of `candidate_ids` are [batch_size, num_candidates, max_len].

**Comment by YuhangXiao1103** [comment]
![image](https://github.com/zjunlp/MolGen/assets/125982410/3023bcc6-fd08-43b4-9e63-2bbb12a2175c)
I tried the format you mention above, but why this crashed?

**Comment by Fangyinfff** [comment]
Hi, 
I think the best way is for you to add breakpoints while running the code I provided and check the shapes and specific contents of both `src_input_ids` and `candidate_ids`.

**Comment by YuhangXiao1103** [comment]
Danke!
