### ISSUE TITLE
Fail to install conda environment

### ISSUE THREAD

**Issue by Kartinaa** [zjunlp/MolGen#14]
Dear author,

Thanks for sharing your wonderful work! When I tried to install the conda environment using `environment.yml` file, I failed because it is not the format that conda needed. However, even if I make the environment file conda-readable, it still gives me error cause some version conflict of packages. 

Really appreciate it if you could help with this. Have a great day!

Best,
Bo

**Comment by Fangyinfff** [comment]
Hi, I think you could install some packages that you haven’t yet by following the `environment.yml` file. The essential ones include `deepspeed`, `selfies`, `torch`, `transformers`, `tqdm`, and `numpy`. If anything is missing, you can install additional packages as needed based on the error messages you receive during runtime.

**Comment by Kartinaa** [comment]
Thanks for the suggestions! I'll try what you suggested.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by Fangyinfff** [comment]
Hi,

I have updated another one: https://github.com/zjunlp/MolGen/blob/main/MolGen/environment.yaml

Please try with: `conda env create -f environment.yaml`

**Comment by zxlzr** [comment]
hi, have you solved your issue yet?
