### ISSUE TITLE
Experiments with Table 2 and 3 in paper

### ISSUE THREAD

**Issue by HuskyNian** [zjunlp/MolGen#15]
Dear authors,
   Great work! How did you conduct the experiments in table 2 and 3 (Target molecular discovery) in the paper? Did you do that in single objective optimization or multi-objective? 

Best

**Comment by Fangyinfff** [comment]
Thank you for your interest. 

The code provided in the project is intended for target molecular discovery, and we use only single-objective optimization.

**Comment by zxlzr** [comment]
hi, do you have any further questions?
