### ISSUE TITLE
where is '../moldata/checkpoint/molgen.pkl'?

### ISSUE THREAD

**Issue by DrugD** [zjunlp/MolGen#16]
The molgen.pkl can not been found, please show its link.

**Comment by Fangyinfff** [comment]
Hi,

You can download the model using the following link: https://drive.google.com/drive/folders/1Eelk_RX1I26qLa9c4SZq6Tv-AAbDXgrW?usp=sharing

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by DrugD** [comment]
none, thanks! :-)
