### ISSUE TITLE
Questions about prefix and chemical feedback

### ISSUE THREAD

**Issue by xxfdgs** [zjunlp/MolGen#17]
Thank you very much for your excellent work. I have a few questions regarding your article and code:

1.Checkpoint File 'molgen.pkl': If I understand correctly, the checkpoint file 'molgen.pkl' provided in the Google Drive link has already completed pretraining stages 1 and 2. Therefore, it seems that I only need to proceed with the fine-tuning phase. Could you kindly confirm if this understanding is accurate?

2.Pretraining Stage 2 Input Format: Regarding pretraining stage 2, which utilizes tunable prefix vectors, I would like to inquire whether the input format remains the same as in stage 1. Specifically, if I use the same dataset as in stage 1, will the model still function correctly, albeit potentially with reduced performance?

3.Model Use for Pharmaceutical Molecules: Based on the fact that penalized logP and QED are used as the property scores when ranking candidates in pretraining stage 2 (please correct me if I am mistaken), I would infer that this model is particularly suited for generating pharmaceutical molecules, where penalized logP and QED are key metrics. Is this correct, or might the model also be applicable to other molecular generation tasks in different domains?

Thank you for your time and any insights you could provide.

**Comment by Fangyinfff** [comment]
Hi, 

Thank you for your interest. Here are my responses to each point:

1. Your understanding is correct; you can directly fine-tune using `molgen.pkl`.
2. The input format is the same as in stage 1. I believe using data that includes both natural products and synthetic molecules might be more appropriate. However, if you only use stage 1 data and your downstream task involves only synthetic molecules, the performance should not be significantly affected.
3. Yes, you can certainly replace it with another property. You’ll need to specify a function to compute the property score for the molecules in your training data or have a dataset where each molecule’s property score is labeled.

I hope this helps.

**Comment by xxfdgs** [comment]
Thank you very much for your helpful responses. I have a further question regarding fine-tuning:

In the fine-tune stage, it’s mentioned that the model uses polop and qed to rank candidates. However, after reviewing the code, I only found the polop and qed functions in generate_ds.py, which appears to be used for dataset generation rather than fine-tuning. I did not see any functions for calculating polop or qed in finetune.py or other fine-tuning-related files.

Could you clarify whether these property-calculating functions are only utilized during molecular generation in generate_ds.py, or are they applied elsewhere beyond that script?

Thank you!

**Comment by Fangyinfff** [comment]
Yes, before fine-tuning, we use the property function to calculate the property of each molecule and rank the molecules based on the property scores. The processed data is then used as input for the model.

**Comment by xxfdgs** [comment]
Thank you four your answer, I will continue to work on this model:)
