### ISSUE TITLE
what is the difference between finetune.py and train_prefix.py in the folder "molgen"?

### ISSUE THREAD

**Issue by jueyuC** [zjunlp/MolGen#18]
Excuse me, I wonder what the difference between finetune.py and train_prefix.py in the folder "molgen" is.

**Comment by Fangyinfff** [comment]
Thank you for your attention.

`train_prefix.py` corresponds to the second phase of pre-training, while `finetune.py` is used for the fine-tuning stage, during which the model is specifically optimized to assign higher generation probabilities to molecules with better property scores.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by jueyuC** [comment]
Thanks much for your answer, I have no further questions~
