### ISSUE TITLE
为什么说 MPT 可以在不同 tasks 和 domains 之间共享知识呢?

### ISSUE THREAD

**Issue by TVect** [zjunlp/MolGen#3]
你好, 请问一下啊, 文章中说 MPT 可以在不同 tasks 和 domains 之间共享知识 是什么意思呢?

使用 MPT 方法, 不也是对每个 QED, p-logP 优化任务单独做参数调整吗?

**Comment by Fangyinfff** [comment]
您好，很抱歉我们之前的表述不够清晰，给您带来了误解。我们已经对该部分进行了修改，但暂时还未在arxiv上更新。

您可以将MPT理解为预训练的第二阶段。我们的具体做法是同时在多个领域的数据上进行MPT训练，这里的训练目标与预训练的第一阶段（在一亿个分子上学习分子的基本语法规则）相同。不同之处在于，我们使用了来自多个领域的数据，并且模型增加了prefix。通过这个过程，MPT学习到了不同领域之间的共享知识。

接下来，我们将预训练所得到的prefix权重作为下游任务中使用的prefix的初始化。在下游任务的微调过程中，我们会对每个QED和p-logP优化任务进行单独的参数调整。这属于下游微调阶段，不属于MPT阶段。

希望能解答您的疑惑！如果您还有其他问题，欢迎提问。

**Comment by TVect** [comment]
谢谢大佬  😄 👍 

所以整个流程是包含三个步骤:

1. 100M zinc molecules 上预训练
2. 多个 tasks + domains 上 MPT
3. 具体任务上再基于 step2 的参数微调

我这样理解对吗?

**Comment by Fangyinfff** [comment]
是的，您的理解是正确的。不过MPT实际上只是在多个domain上做的，没有涉及到task，因为MPT阶段和第一阶段的预训练目标是一致的。

**Comment by TVect** [comment]
👌 了解了 😄 非常感谢 🙏 🙏

**Comment by Fangyinfff** [comment]
不客气☺️ 感谢关注
