### ISSUE TITLE
Question about ”generation of two-dimensional molecules“

### ISSUE THREAD

**Issue by yangzhao1230** [zjunlp/MolGen#4]
Hi, thanks for you great work.

In your paper, you mentioned that this work is focused on two-dimensional molecules. From my understanding, two-dimensional molecules refer to molecules represented using a graph data structure. I would like to know the reason behind using this term.

**Comment by Fangyinfff** [comment]
Thank you for your thoughtful question.

In our research, we use the term "two-dimensional molecules" to primarily distinguish it from the "three-dimensional molecules" data, the latter of which incorporates additional spatial details, such as atomic coordinates.

When we refer to "two-dimensional molecules" in our paper, we mean representations that can effectively portray the topological structure of the molecules. These forms, such as molecular graphs and sequences, effectively delineate the structural arrangement of atoms and the types of bonds between them, as well as the various substructures within the molecule. 

I hope this is more clear, and I'm happy to further elaborate if needed.

**Comment by yangzhao1230** [comment]
Thanks！
