### ISSUE TITLE
Reduntant import

### ISSUE THREAD

**Issue by zkysfls** [zjunlp/MolGen#5]
Hi, I see that you have import numpy, warning and selfies multiple times in generate_ds.py

![7](https://github.com/zjunlp/MolGen/assets/26270894/5a858ff0-4e48-434d-9543-473aaecdd036)

**Comment by Fangyinfff** [comment]
Hi, thanks for bringing this to my attention! It seems to be an oversight. The unnecessary multiple imports of numpy, warning, and selfies have been removed for cleaner and more efficient code. Thanks for pointing out this improvement.
