### ISSUE TITLE
Pretrain and finetune datasets 

### ISSUE THREAD

**Issue by carlosFir** [zjunlp/MolGen#6]
Really thanks for your great code and essay. 
When I was trying to do the project, questions came to me like the usage of the different datasets, the input/output things and the time it consumes. 
For datasets confusions, it is obvious that 100M data from ZINC15 were selected for pretraining but there are several datasets files in dir "finetune" which confuse me. I am just wondering, in order to achieve the whole process, which one should be used for pretraining and which for finetune under the multi-task environment. 
Otherwise, about the time,  I checked 250,000 data running on our device(usage of 3 V100s, 16GB) and it turned out to be in 2-3 days to complete the whole process. And you mentioned 6 V100s were used for training, so i was wondering how long it took to pretrain your model on 100M ZINC15 dataset as my personal reference.
Last, I've seen the .sh files in your dir, it bothered me whether the defaulted parameters in it need to be fixed or not, including the datasets path... because I found some path or files' names didn't exist in the project...
Thanks for noticing this :)

**Comment by Fangyinfff** [comment]
Hi, thank you for your interest in our work and your questions. Our project did not initially release the pretraining code, so the guidelines for pretraining were not included in our README. We understand that the data organization can be a bit confusing and we're working to improve the clarity. Here are the specific answers to your questions:

1. The pre-training stage involves two steps. 

- The first step uses [100M molecules](https://az.app.box.com/s/7eci3nd9vy0xplqniitpk02rbg9q2zcq/folder/144882783357) from the ZINC15 database, which can be downloaded from the [Chemformer project page](https://github.com/MolecularAI/Chemformer). Note that you need to preprocess this dataset to convert the SMILES representation to SELFIES and remove empty lines.
- The second stage of pretraining uses the `zinc250k.csv`, [MOSES](https://github.com/molecularsets/moses/blob/master/data/dataset_v1.csv), and `nature_product.csv`, which have been moved to a [new directory](https://github.com/zjunlp/MolGen/tree/main/moldata/pretrain). We will update the documentation to reflect this change soon. Note that you also need to preprocess the MOSES dataset to convert the SMILES representation to SELFIES and remove empty lines.

2. The [finetune directory](https://github.com/zjunlp/MolGen/tree/main/moldata/finetune) contains data for downstream tasks, specifically for molecular optimization tasks.

3. Lastly, concerning the .sh files, we are aware that some default parameters and paths might be outdated. These are there mostly for reference and you should update the dataset paths and parameters according to your specific needs and dataset locations. We will look into updating these script files to avoid any confusion in the future.

We hope this clears up your doubts, and we appreciate your patience as we work to improve the documentation and code. Let us know if you have any further questions!

**Comment by carlosFir** [comment]
Thanks a lot for your work!
