### ISSUE TITLE
Details on Mol-Gen 7b

### ISSUE THREAD

**Issue by acharkq** [zjunlp/MolGen#7]
Hi Authors,

Congratulations on your outstanding work. MolGen is an invaluable contribution to the field of molecule generation.

I am particularly interested in understanding the training intricacies of the recently released LM Mol-Gen 7b. Specifically, I have a few questions:

* Is it trained from scratch or initialized from Meta's Llama-7b?
* Is it trained solely for molecule generation or trained jointly with other objectives?
* How large is the training corpus?

Your insights would greatly enrich my understanding of the model's architecture and training strategy. I look forward to your response.

**Comment by Fangyinfff** [comment]
Thank you for your interest and kind words. 

MolGen-7b was trained from scratch, specifically for molecular generation. The pre-training data consists of over a hundred million molecules. 

I hope this addresses your concerns!

**Comment by acharkq** [comment]
Thanks for the prompt response!
